version: "3.11"

services:
  web:
    build: .
    container_name: converter-app
    command: gunicorn your_project_name.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    working_dir: /app
